import { StyleSheet, Dimensions } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

const grey = '#2B2B2B';
const greyDark = '#1A1A1A';
const lightGrey = '#E0E0E0';
const red = '#C62828';
const redDark = '#8E1B1B';

export const gameStyles = (insets: ReturnType<typeof useSafeAreaInsets>) =>
  StyleSheet.create({
    flex: {
      flex: 1,
      backgroundColor: 'transparent',
      justifyContent: 'flex-end',
    },
    hudRow: {
      position: 'absolute',
      top: insets.top + 10,
      left: 20,
      right: 20,
      height: 40,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      zIndex: 10,
    },
    hudText: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 14,
      color: lightGrey,
    },
    card: {
      backgroundColor: '#0F1518',
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: insets.bottom + 20,
      width: '100%',
    },
    road: {
      width: '100%',
      height: Math.floor(Dimensions.get('window').height * 0.62),
      minHeight: 420,
      backgroundColor: '#0B1013',
      borderWidth: 4,
      borderColor: '#2F3B47',
      borderRadius: 12,
      overflow: 'hidden',
    },
    hudInside: {
      position: 'absolute',
      top: 10,
      left: 10,
      right: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      zIndex: 3,
    },
    heartsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    heart: {
      width: 16,
      height: 16,
      backgroundColor: red,
      borderWidth: 3,
      borderColor: redDark,
      borderRadius: 4,
    },
    centerLine: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: '50%',
      width: 4,
      marginLeft: -2,
      backgroundColor: '#4A5A6A',
      opacity: 0.6,
    },
    overlayCard: {
      position: 'absolute',
      left: 20,
      right: 20,
      top: '25%',
      backgroundColor: grey,
      borderWidth: 4,
      borderColor: greyDark,
      borderRadius: 12,
      paddingHorizontal: 20,
      paddingVertical: 20,
      alignItems: 'center',
      zIndex: 4,
      gap: 12,
    },
    overlayTitle: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 28,
      color: lightGrey,
      textAlign: 'center',
      marginBottom: 6,
    },
    overlaySub: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 16,
      color: lightGrey,
      textAlign: 'center',
    },
    overlayHint: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 12,
      color: '#BFC7CE',
      textAlign: 'center',
      marginTop: 4,
    },
    overlayRow: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
      marginTop: 6,
    },
    overlayButton: {
      flex: 1,
      backgroundColor: red,
      borderWidth: 4,
      borderColor: redDark,
      borderRadius: 8,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 12,
    },
    overlayButtonText: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 18,
      color: lightGrey,
    },
    returnButtonContainer: {
      width: '100%',
      paddingHorizontal: 20,
      paddingBottom: insets.bottom + 12,
      paddingTop: 8,
      backgroundColor: 'transparent',
    },
    returnButton: {
      backgroundColor: '#4A5A6A',
      borderWidth: 4,
      borderColor: '#2F3B47',
      borderRadius: 6,
      alignItems: 'center',
      justifyContent: 'center',
      height: 56,
      width: '100%',
    },
    returnText: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 18,
      color: lightGrey,
    },
  });
