import { StyleSheet } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

const red = '#C62828';
const redDark = '#8E1B1B';
const grey = '#2B2B2B';
const greyDark = '#1A1A1A';
const lightGrey = '#E0E0E0';

export const menuStyles = (insets: ReturnType<typeof useSafeAreaInsets>) =>
  StyleSheet.create({
    flex: {
      flex: 1,
      backgroundColor: 'transparent',
      paddingTop: insets.top + 20,
    },
    topRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginHorizontal: 20,
      marginBottom: 20,
    },
    infoCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: grey,
      borderWidth: 4,
      borderColor: greyDark,
      borderRadius: 6,
      paddingHorizontal: 12,
      paddingVertical: 6,
      gap: 8,
    },
    infoText: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 16,
      color: '#fff',
    },
    flagIcon: {
      width: 28,
      height: 18,
    },
    coinIcon: {
      width: 22,
      height: 22,
    },
    bottomSection: {
      position: 'absolute',
      bottom: insets.bottom + 20,
      left: 0,
      right: 0,
      alignItems: 'center',
      gap: 20,
    },
    startButtons: {
      width: '100%',
      alignItems: 'center',
      gap: 12,
    },
    pixelButtonOuter: {
      width: '72%',
      height: 64,
      backgroundColor: red,
      borderWidth: 4,
      borderColor: redDark,
      borderRadius: 6,
      justifyContent: 'center',
      alignItems: 'center',
    },
    pixelButtonInner: {
      flex: 1,
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
    },
    pixelButtonOuterGrey: {
      width: '72%',
      height: 50,
      backgroundColor: grey,
      borderWidth: 4,
      borderColor: greyDark,
      borderRadius: 6,
      justifyContent: 'center',
      alignItems: 'center',
    },
    pixelButtonInnerGrey: {
      flex: 1,
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
    },
    startButtonDisabled: {
      opacity: 0.6,
    },
    startButtonText: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 22,
      color: lightGrey,
    },
    startButtonTextSmall: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 16,
      color: lightGrey,
    },
    menuRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'flex-start',
      gap: 22,
      marginTop: 10,
    },
    navItem: {
      alignItems: 'center',
    },
    navButtonOuter: {
      width: 58,
      height: 58,
      backgroundColor: grey,
      borderWidth: 4,
      borderColor: greyDark,
      borderRadius: 6,
      justifyContent: 'center',
      alignItems: 'center',
    },
    navButtonInner: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
    },
    navIcon: {
      width: 32,
      height: 32,
      resizeMode: 'contain',
    },
    navLabel: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 10,
      color: lightGrey,
      marginTop: 4,
    },
    loginToast: {
      position: 'absolute',
      top: insets.top + 10,
      left: 20,
      right: 20,
      backgroundColor: grey,
      borderWidth: 4,
      borderColor: greyDark,
      borderRadius: 6,
      paddingHorizontal: 12,
      paddingVertical: 10,
      zIndex: 10,
    },
    loginToastText: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 14,
      color: lightGrey,
      textAlign: 'center',
    },
    editOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      justifyContent: 'flex-end',
    },
    editCard: {
      backgroundColor: '#0F1518',
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingHorizontal: 20,
      paddingBottom: insets.bottom + 20,
      paddingTop: 10,
      width: '100%',
    },
    dragHandleWrapper: {
      alignItems: 'center',
      marginTop: 10,
      marginBottom: 20,
    },
    dragHandle: {
      width: 40,
      height: 5,
      borderRadius: 3,
      backgroundColor: '#4A5A6A',
    },
    editHeading: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 28,
      color: lightGrey,
      textAlign: 'center',
      marginBottom: 30,
    },
    editFormSection: {
      gap: 16,
      marginBottom: 20,
    },
    input: {
      backgroundColor: grey,
      borderWidth: 4,
      borderColor: greyDark,
      borderRadius: 6,
      paddingHorizontal: 12,
      height: 48,
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 14,
      color: lightGrey,
    },
    dropdownToggle: {
      backgroundColor: grey,
      borderWidth: 4,
      borderColor: greyDark,
      borderRadius: 6,
      paddingHorizontal: 12,
      height: 48,
      justifyContent: 'center',
    },
    dropdownToggleText: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 14,
      color: lightGrey,
    },
    dropdown: {
      backgroundColor: grey,
      borderWidth: 4,
      borderColor: greyDark,
      borderRadius: 6,
    },
    countryRow: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 8,
      borderBottomWidth: 1,
      borderBottomColor: greyDark,
    },
    countryRowCompact: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    flagSmall: {
      width: 24,
      height: 16,
      borderRadius: 2,
      backgroundColor: greyDark,
    },
    countryName: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 14,
      color: lightGrey,
      marginLeft: 8,
    },
    bottomButtonsRow: {
      gap: 16,
    },
    primaryButton: {
      backgroundColor: red,
      borderWidth: 4,
      borderColor: redDark,
      borderRadius: 6,
      alignItems: 'center',
      justifyContent: 'center',
      height: 56,
      width: '100%',
    },
    primaryButtonText: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 18,
      color: lightGrey,
    },
    returnButton: {
      backgroundColor: '#4A5A6A',
      borderWidth: 4,
      borderColor: '#2F3B47',
      borderRadius: 6,
      alignItems: 'center',
      justifyContent: 'center',
      height: 56,
      width: '100%',
    },
    returnText: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 18,
      color: lightGrey,
    },
  });
