import { StyleSheet } from 'react-native';
import { EdgeInsets } from 'react-native-safe-area-context';

const lightGrey = '#E0E0E0';
const sheetBg = '#0F1518';
const grey = '#2B2B2B';
const greyDark = '#1A1A1A';
const handleBlue = '#4A5A6A';
const handleBlueDark = '#2F3B47';
const chipBg = '#0B1114';

export const multiplayerStyles = (insets: EdgeInsets) =>
  StyleSheet.create({
    flex: {
      flex: 1,
      backgroundColor: 'transparent',
      justifyContent: 'flex-end',
    },
    card: {
      backgroundColor: sheetBg,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingHorizontal: 20,
      paddingBottom: insets.bottom + 20,
      paddingTop: 10,
      width: '100%',
    },
    dragHandleWrapper: {
      alignItems: 'center',
      marginTop: 10,
      marginBottom: 20,
    },
    dragHandle: {
      width: 40,
      height: 5,
      borderRadius: 3,
      backgroundColor: handleBlue,
    },
    heading: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 28,
      color: lightGrey,
      textAlign: 'center',
      marginBottom: 20,
    },
    bottomSection: {
      marginTop: 20,
      gap: 16,
    },
    primaryButton: {
      backgroundColor: grey,
      borderWidth: 4,
      borderColor: greyDark,
      borderRadius: 6,
      alignItems: 'center',
      justifyContent: 'center',
      height: 56,
      width: '100%',
    },
    primaryButtonText: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 18,
      color: lightGrey,
    },
    disabled: {
      opacity: 0.5,
    },
    returnButton: {
      backgroundColor: handleBlue,
      borderWidth: 4,
      borderColor: handleBlueDark,
      borderRadius: 6,
      alignItems: 'center',
      justifyContent: 'center',
      height: 56,
      width: '100%',
    },
    returnText: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 18,
      color: lightGrey,
    },
    qrWrapOuter: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    qrWhiteBox: {
      width: 260,
      height: 260,
      borderRadius: 12,
      borderWidth: 4,
      borderColor: handleBlueDark,
      backgroundColor: '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
    },
    codeText: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 16,
      color: lightGrey,
      textAlign: 'center',
      marginTop: 12,
    },
    noticeBox: {
      marginTop: 14,
      borderRadius: 8,
      borderWidth: 4,
      borderColor: handleBlueDark,
      backgroundColor: chipBg,
      paddingVertical: 12,
      paddingHorizontal: 12,
    },
    noticeText: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 14,
      color: lightGrey,
      textAlign: 'center',
    },
    rowButtons: {
      flexDirection: 'row',
      gap: 12,
      marginTop: 16,
    },
    cancelButton: {
      flex: 1,
      backgroundColor: grey,
      borderWidth: 4,
      borderColor: greyDark,
      borderRadius: 6,
      alignItems: 'center',
      justifyContent: 'center',
      height: 56,
    },
    cancelButtonText: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 18,
      color: lightGrey,
    },
    blueButton: {
      flex: 1,
      backgroundColor: handleBlue,
      borderWidth: 4,
      borderColor: handleBlueDark,
      borderRadius: 6,
      alignItems: 'center',
      justifyContent: 'center',
      height: 56,
    },
    blueButtonText: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 18,
      color: lightGrey,
    },
    disabledButton: {
      flex: 1,
      backgroundColor: grey,
      borderWidth: 4,
      borderColor: greyDark,
      borderRadius: 6,
      alignItems: 'center',
      justifyContent: 'center',
      height: 56,
      opacity: 0.6,
    },
    scannerWrap: {
      overflow: 'hidden',
      borderRadius: 10,
      borderWidth: 4,
      borderColor: handleBlueDark,
      height: 300,
      backgroundColor: chipBg,
      position: 'relative',
    },
    scannerControls: {
      position: 'absolute',
      bottom: 10,
      left: 10,
      right: 10,
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 12,
    },
    controlBtn: {
      backgroundColor: '#1F2830',
      borderWidth: 3,
      borderColor: handleBlueDark,
      borderRadius: 6,
      paddingHorizontal: 12,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    controlBtnText: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 12,
      color: lightGrey,
    },
    centerBox: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    helperText: {
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 12,
      color: lightGrey,
      textAlign: 'center',
      marginTop: 10,
      opacity: 0.8,
    },
    input: {
      backgroundColor: chipBg,
      borderWidth: 4,
      borderColor: handleBlueDark,
      borderRadius: 8,
      paddingHorizontal: 12,
      height: 48,
      color: lightGrey,
      fontFamily: 'Silkscreen_400Regular',
      fontSize: 14,
      marginTop: 10,
    },
  });
