export const countryList = [
  { code: 'us', name: 'United States', flag: require('../assets/flags/us.png') },
  { code: 'za', name: 'South Africa', flag: require('../assets/flags/za.png') },
  { code: 'gb', name: 'United Kingdom', flag: require('../assets/flags/gb.png') },
  { code: 'fr', name: 'France', flag: require('../assets/flags/fr.png') },
  { code: 'de', name: 'Germany', flag: require('../assets/flags/de.png') },
  { code: 'it', name: 'Italy', flag: require('../assets/flags/it.png') },
  { code: 'ng', name: 'Nigeria', flag: require('../assets/flags/ng.png') },
  { code: 'br', name: 'Brazil', flag: require('../assets/flags/br.png') },
  { code: 'in', name: 'India', flag: require('../assets/flags/in.png') },
  { code: 'cn', name: 'China', flag: require('../assets/flags/cn.png') },
  { code: 'jp', name: 'Japan', flag: require('../assets/flags/jp.png') },
  { code: 'kr', name: 'South Korea', flag: require('../assets/flags/kr.png') },
  { code: 'ru', name: 'Russia', flag: require('../assets/flags/ru.png') },
  { code: 'ke', name: 'Kenya', flag: require('../assets/flags/ke.png') },
  { code: 'eg', name: 'Egypt', flag: require('../assets/flags/eg.png') },
  { code: 'au', name: 'Australia', flag: require('../assets/flags/au.png') },
  { code: 'ca', name: 'Canada', flag: require('../assets/flags/ca.png') },
  { code: 'es', name: 'Spain', flag: require('../assets/flags/es.png') },
  { code: 'mx', name: 'Mexico', flag: require('../assets/flags/mx.png') },
  { code: 'ar', name: 'Argentina', flag: require('../assets/flags/ar.png') },
  { code: 'gh', name: 'Ghana', flag: require('../assets/flags/gh.png') },
];
